services:
    _defaults:
        public: false

    Tequila\Bundle\SwaggerBundle\Generator\AnnotationsBasedGenerator:
        tags: ['tequila.swagger.generator']

    tequila_swagger.controller.docs_ui:
        class: Tequila\Bundle\SwaggerBundle\Controller\DocsUiController
        arguments: ['%kernel.root_dir%']
        public: true
        tags: ['controller.service_arguments']

    Tequila\Bundle\SwaggerBundle\Command\GenerateJsonCommand:
        arguments:
            - '@Tequila\Bundle\SwaggerBundle\Generator\GeneratorsChain'
            - '%kernel.root_dir%'
        tags:
            - { name: 'console.command', command: tequila_swagger:generate:json }

    Tequila\Bundle\SwaggerBundle\Generator\GeneratorsChain:
        arguments:
            - '@event_dispatcher'
            - !tagged 'tequila.swagger.generator'

    Tequila\Bundle\SwaggerBundle\EventListener\FilterPathsSubscriber:
        arguments: ['%tequila_swagger.path_patterns%']
        tags: ['kernel.event_subscriber']
